module.exports = {
  'r_tech_1': { id: 'r_tech_1', name: 'Réseau de Neurones', cost: 1800, desc: 'Avancée majeure en Tech.', req: ['r_quantum'] },
  'r_tech_2': { id: 'r_tech_2', name: 'IA Forte', cost: 2700, desc: 'Avancée majeure en Tech.', req: ['r_tech_1'] },
  'r_tech_3': { id: 'r_tech_3', name: 'Singularité', cost: 4200, desc: 'Avancée majeure en Tech.', req: ['r_tech_2'] },
  'r_tech_4': { id: 'r_tech_4', name: 'Nano-robots', cost: 6300, desc: 'Avancée majeure en Tech.', req: ['r_tech_3'] },
  'r_tech_5': { id: 'r_tech_5', name: 'Dyson Sphere', cost: 9000, desc: 'Avancée majeure en Tech.', req: ['r_tech_4'] },
  'r_tech_6': { id: 'r_tech_6', name: 'Matriochka Brain', cost: 12300, desc: 'Avancée majeure en Tech.', req: ['r_tech_5'] },
  'r_tech_7': { id: 'r_tech_7', name: 'Vitesse Lumière', cost: 16200, desc: 'Avancée majeure en Tech.', req: ['r_tech_6'] },
  'r_tech_8': { id: 'r_tech_8', name: 'Téléportation', cost: 20700, desc: 'Avancée majeure en Tech.', req: ['r_tech_7'] },
  'r_tech_9': { id: 'r_tech_9', name: 'Réalité Simulée', cost: 25800, desc: 'Avancée majeure en Tech.', req: ['r_tech_8'] },
  'r_tech_10': { id: 'r_tech_10', name: 'Réseau de Neurones Mk2', cost: 31500, desc: 'Avancée majeure en Tech.', req: ['r_tech_9'] },
  'r_tech_11': { id: 'r_tech_11', name: 'IA Forte Mk2', cost: 37800, desc: 'Avancée majeure en Tech.', req: ['r_tech_10'] },
  'r_tech_12': { id: 'r_tech_12', name: 'Singularité Mk2', cost: 44700, desc: 'Avancée majeure en Tech.', req: ['r_tech_11'] },
  'r_tech_13': { id: 'r_tech_13', name: 'Nano-robots Mk2', cost: 52200, desc: 'Avancée majeure en Tech.', req: ['r_tech_12'] },
  'r_tech_14': { id: 'r_tech_14', name: 'Dyson Sphere Mk2', cost: 60300, desc: 'Avancée majeure en Tech.', req: ['r_tech_13'] },
  'r_tech_15': { id: 'r_tech_15', name: 'Matriochka Brain Mk2', cost: 69000, desc: 'Avancée majeure en Tech.', req: ['r_tech_14'] },
  'r_tech_16': { id: 'r_tech_16', name: 'Vitesse Lumière Mk2', cost: 78300, desc: 'Avancée majeure en Tech.', req: ['r_tech_15'] },
  'r_tech_17': { id: 'r_tech_17', name: 'Téléportation Mk2', cost: 88200, desc: 'Avancée majeure en Tech.', req: ['r_tech_16'] },
  'r_tech_18': { id: 'r_tech_18', name: 'Réalité Simulée Mk2', cost: 98700, desc: 'Avancée majeure en Tech.', req: ['r_tech_17'] },
  'r_tech_19': { id: 'r_tech_19', name: 'Réseau de Neurones Mk3', cost: 109800, desc: 'Avancée majeure en Tech.', req: ['r_tech_18'] },
  'r_tech_20': { id: 'r_tech_20', name: 'IA Forte Mk3', cost: 121500, desc: 'Avancée majeure en Tech.', req: ['r_tech_19'] },
  'r_tech_21': { id: 'r_tech_21', name: 'Singularité Mk3', cost: 133800, desc: 'Avancée majeure en Tech.', req: ['r_tech_20'] },
  'r_tech_22': { id: 'r_tech_22', name: 'Nano-robots Mk3', cost: 146700, desc: 'Avancée majeure en Tech.', req: ['r_tech_21'] },
  'r_tech_23': { id: 'r_tech_23', name: 'Dyson Sphere Mk3', cost: 160200, desc: 'Avancée majeure en Tech.', req: ['r_tech_22'] },
  'r_tech_24': { id: 'r_tech_24', name: 'Matriochka Brain Mk3', cost: 174300, desc: 'Avancée majeure en Tech.', req: ['r_tech_23'] },
  'r_tech_25': { id: 'r_tech_25', name: 'Vitesse Lumière Mk3', cost: 189000, desc: 'Avancée majeure en Tech.', req: ['r_tech_24'] },
  'r_tech_26': { id: 'r_tech_26', name: 'Téléportation Mk3', cost: 204300, desc: 'Avancée majeure en Tech.', req: ['r_tech_25'] },
  'r_tech_27': { id: 'r_tech_27', name: 'Réalité Simulée Mk3', cost: 220200, desc: 'Avancée majeure en Tech.', req: ['r_tech_26'] },
  'r_tech_28': { id: 'r_tech_28', name: 'Réseau de Neurones Mk4', cost: 236700, desc: 'Avancée majeure en Tech.', req: ['r_tech_27'] },
  'r_tech_29': { id: 'r_tech_29', name: 'IA Forte Mk4', cost: 253800, desc: 'Avancée majeure en Tech.', req: ['r_tech_28'] },
  'r_tech_30': { id: 'r_tech_30', name: 'Singularité Mk4', cost: 271500, desc: 'Avancée majeure en Tech.', req: ['r_tech_29'] },
  'r_bio_1': { id: 'r_bio_1', name: 'Modification Génétique', cost: 1800, desc: 'Avancée majeure en Bio.', req: ['r_cloning'] },
  'r_bio_2': { id: 'r_bio_2', name: 'Immortalité', cost: 2700, desc: 'Avancée majeure en Bio.', req: ['r_bio_1'] },
  'r_bio_3': { id: 'r_bio_3', name: 'Transhumanisme', cost: 4200, desc: 'Avancée majeure en Bio.', req: ['r_bio_2'] },
  'r_bio_4': { id: 'r_bio_4', name: 'Conscience Téléchargée', cost: 6300, desc: 'Avancée majeure en Bio.', req: ['r_bio_3'] },
  'r_bio_5': { id: 'r_bio_5', name: 'Amélioration Cognitive', cost: 9000, desc: 'Avancée majeure en Bio.', req: ['r_bio_4'] },
  'r_bio_6': { id: 'r_bio_6', name: 'Espérance de vie +100', cost: 12300, desc: 'Avancée majeure en Bio.', req: ['r_bio_5'] },
  'r_bio_7': { id: 'r_bio_7', name: 'Photosynthèse Humaine', cost: 16200, desc: 'Avancée majeure en Bio.', req: ['r_bio_6'] },
  'r_bio_8': { id: 'r_bio_8', name: 'Régénération Cellulaire', cost: 20700, desc: 'Avancée majeure en Bio.', req: ['r_bio_7'] },
  'r_bio_9': { id: 'r_bio_9', name: 'Modification Génétique Mk2', cost: 25800, desc: 'Avancée majeure en Bio.', req: ['r_bio_8'] },
  'r_bio_10': { id: 'r_bio_10', name: 'Immortalité Mk2', cost: 31500, desc: 'Avancée majeure en Bio.', req: ['r_bio_9'] },
  'r_bio_11': { id: 'r_bio_11', name: 'Transhumanisme Mk2', cost: 37800, desc: 'Avancée majeure en Bio.', req: ['r_bio_10'] },
  'r_bio_12': { id: 'r_bio_12', name: 'Conscience Téléchargée Mk2', cost: 44700, desc: 'Avancée majeure en Bio.', req: ['r_bio_11'] },
  'r_bio_13': { id: 'r_bio_13', name: 'Amélioration Cognitive Mk2', cost: 52200, desc: 'Avancée majeure en Bio.', req: ['r_bio_12'] },
  'r_bio_14': { id: 'r_bio_14', name: 'Espérance de vie +100 Mk2', cost: 60300, desc: 'Avancée majeure en Bio.', req: ['r_bio_13'] },
  'r_bio_15': { id: 'r_bio_15', name: 'Photosynthèse Humaine Mk2', cost: 69000, desc: 'Avancée majeure en Bio.', req: ['r_bio_14'] },
  'r_bio_16': { id: 'r_bio_16', name: 'Régénération Cellulaire Mk2', cost: 78300, desc: 'Avancée majeure en Bio.', req: ['r_bio_15'] },
  'r_bio_17': { id: 'r_bio_17', name: 'Modification Génétique Mk3', cost: 88200, desc: 'Avancée majeure en Bio.', req: ['r_bio_16'] },
  'r_bio_18': { id: 'r_bio_18', name: 'Immortalité Mk3', cost: 98700, desc: 'Avancée majeure en Bio.', req: ['r_bio_17'] },
  'r_bio_19': { id: 'r_bio_19', name: 'Transhumanisme Mk3', cost: 109800, desc: 'Avancée majeure en Bio.', req: ['r_bio_18'] },
  'r_bio_20': { id: 'r_bio_20', name: 'Conscience Téléchargée Mk3', cost: 121500, desc: 'Avancée majeure en Bio.', req: ['r_bio_19'] },
  'r_bio_21': { id: 'r_bio_21', name: 'Amélioration Cognitive Mk3', cost: 133800, desc: 'Avancée majeure en Bio.', req: ['r_bio_20'] },
  'r_bio_22': { id: 'r_bio_22', name: 'Espérance de vie +100 Mk3', cost: 146700, desc: 'Avancée majeure en Bio.', req: ['r_bio_21'] },
  'r_bio_23': { id: 'r_bio_23', name: 'Photosynthèse Humaine Mk3', cost: 160200, desc: 'Avancée majeure en Bio.', req: ['r_bio_22'] },
  'r_bio_24': { id: 'r_bio_24', name: 'Régénération Cellulaire Mk3', cost: 174300, desc: 'Avancée majeure en Bio.', req: ['r_bio_23'] },
  'r_bio_25': { id: 'r_bio_25', name: 'Modification Génétique Mk4', cost: 189000, desc: 'Avancée majeure en Bio.', req: ['r_bio_24'] },
  'r_bio_26': { id: 'r_bio_26', name: 'Immortalité Mk4', cost: 204300, desc: 'Avancée majeure en Bio.', req: ['r_bio_25'] },
  'r_bio_27': { id: 'r_bio_27', name: 'Transhumanisme Mk4', cost: 220200, desc: 'Avancée majeure en Bio.', req: ['r_bio_26'] },
  'r_bio_28': { id: 'r_bio_28', name: 'Conscience Téléchargée Mk4', cost: 236700, desc: 'Avancée majeure en Bio.', req: ['r_bio_27'] },
  'r_bio_29': { id: 'r_bio_29', name: 'Amélioration Cognitive Mk4', cost: 253800, desc: 'Avancée majeure en Bio.', req: ['r_bio_28'] },
  'r_bio_30': { id: 'r_bio_30', name: 'Espérance de vie +100 Mk4', cost: 271500, desc: 'Avancée majeure en Bio.', req: ['r_bio_29'] },
  'r_cosmic_1': { id: 'r_cosmic_1', name: 'Base Astéroïde', cost: 5800, desc: 'Avancée majeure en Cosmic.', req: ['r_mars'] },
  'r_cosmic_2': { id: 'r_cosmic_2', name: 'Terraformation', cost: 6700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_1'] },
  'r_cosmic_3': { id: 'r_cosmic_3', name: 'Colonie Alpha Centauri', cost: 8200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_2'] },
  'r_cosmic_4': { id: 'r_cosmic_4', name: 'Extraction de Matière Noire', cost: 10300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_3'] },
  'r_cosmic_5': { id: 'r_cosmic_5', name: 'Trous de Ver', cost: 13000, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_4'] },
  'r_cosmic_6': { id: 'r_cosmic_6', name: 'Commerce Intergalactique', cost: 16300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_5'] },
  'r_cosmic_7': { id: 'r_cosmic_7', name: 'Empire Galactique', cost: 20200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_6'] },
  'r_cosmic_8': { id: 'r_cosmic_8', name: 'Ascension Dimensionnelle', cost: 24700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_7'] },
  'r_cosmic_9': { id: 'r_cosmic_9', name: 'Base Astéroïde Mk2', cost: 29800, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_8'] },
  'r_cosmic_10': { id: 'r_cosmic_10', name: 'Terraformation Mk2', cost: 35500, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_9'] },
  'r_cosmic_11': { id: 'r_cosmic_11', name: 'Colonie Alpha Centauri Mk2', cost: 41800, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_10'] },
  'r_cosmic_12': { id: 'r_cosmic_12', name: 'Extraction de Matière Noire Mk2', cost: 48700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_11'] },
  'r_cosmic_13': { id: 'r_cosmic_13', name: 'Trous de Ver Mk2', cost: 56200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_12'] },
  'r_cosmic_14': { id: 'r_cosmic_14', name: 'Commerce Intergalactique Mk2', cost: 64300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_13'] },
  'r_cosmic_15': { id: 'r_cosmic_15', name: 'Empire Galactique Mk2', cost: 73000, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_14'] },
  'r_cosmic_16': { id: 'r_cosmic_16', name: 'Ascension Dimensionnelle Mk2', cost: 82300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_15'] },
  'r_cosmic_17': { id: 'r_cosmic_17', name: 'Base Astéroïde Mk3', cost: 92200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_16'] },
  'r_cosmic_18': { id: 'r_cosmic_18', name: 'Terraformation Mk3', cost: 102700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_17'] },
  'r_cosmic_19': { id: 'r_cosmic_19', name: 'Colonie Alpha Centauri Mk3', cost: 113800, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_18'] },
  'r_cosmic_20': { id: 'r_cosmic_20', name: 'Extraction de Matière Noire Mk3', cost: 125500, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_19'] },
  'r_cosmic_21': { id: 'r_cosmic_21', name: 'Trous de Ver Mk3', cost: 137800, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_20'] },
  'r_cosmic_22': { id: 'r_cosmic_22', name: 'Commerce Intergalactique Mk3', cost: 150700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_21'] },
  'r_cosmic_23': { id: 'r_cosmic_23', name: 'Empire Galactique Mk3', cost: 164200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_22'] },
  'r_cosmic_24': { id: 'r_cosmic_24', name: 'Ascension Dimensionnelle Mk3', cost: 178300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_23'] },
  'r_cosmic_25': { id: 'r_cosmic_25', name: 'Base Astéroïde Mk4', cost: 193000, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_24'] },
  'r_cosmic_26': { id: 'r_cosmic_26', name: 'Terraformation Mk4', cost: 208300, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_25'] },
  'r_cosmic_27': { id: 'r_cosmic_27', name: 'Colonie Alpha Centauri Mk4', cost: 224200, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_26'] },
  'r_cosmic_28': { id: 'r_cosmic_28', name: 'Extraction de Matière Noire Mk4', cost: 240700, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_27'] },
  'r_cosmic_29': { id: 'r_cosmic_29', name: 'Trous de Ver Mk4', cost: 257800, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_28'] },
  'r_cosmic_30': { id: 'r_cosmic_30', name: 'Commerce Intergalactique Mk4', cost: 275500, desc: 'Avancée majeure en Cosmic.', req: ['r_cosmic_29'] },
  'r_finance_1': { id: 'r_finance_1', name: 'Monnaie Universelle', cost: 1800, desc: 'Avancée majeure en Finance.', req: ['r_tax_haven'] },
  'r_finance_2': { id: 'r_finance_2', name: 'Capitalisme Absolu', cost: 2700, desc: 'Avancée majeure en Finance.', req: ['r_finance_1'] },
  'r_finance_3': { id: 'r_finance_3', name: 'Optimisation Quantique', cost: 4200, desc: 'Avancée majeure en Finance.', req: ['r_finance_2'] },
  'r_finance_4': { id: 'r_finance_4', name: 'Asservissement par la Dette', cost: 6300, desc: 'Avancée majeure en Finance.', req: ['r_finance_3'] },
  'r_finance_5': { id: 'r_finance_5', name: 'Achat de Planètes', cost: 9000, desc: 'Avancée majeure en Finance.', req: ['r_finance_4'] },
  'r_finance_6': { id: 'r_finance_6', name: 'Monopole de l'Univers', cost: 12300, desc: 'Avancée majeure en Finance.', req: ['r_finance_5'] },
  'r_finance_7': { id: 'r_finance_7', name: 'Hyper-inflation Maîtrisée', cost: 16200, desc: 'Avancée majeure en Finance.', req: ['r_finance_6'] },
  'r_finance_8': { id: 'r_finance_8', name: 'Monnaie Universelle Mk2', cost: 20700, desc: 'Avancée majeure en Finance.', req: ['r_finance_7'] },
  'r_finance_9': { id: 'r_finance_9', name: 'Capitalisme Absolu Mk2', cost: 25800, desc: 'Avancée majeure en Finance.', req: ['r_finance_8'] },
  'r_finance_10': { id: 'r_finance_10', name: 'Optimisation Quantique Mk2', cost: 31500, desc: 'Avancée majeure en Finance.', req: ['r_finance_9'] },
  'r_finance_11': { id: 'r_finance_11', name: 'Asservissement par la Dette Mk2', cost: 37800, desc: 'Avancée majeure en Finance.', req: ['r_finance_10'] },
  'r_finance_12': { id: 'r_finance_12', name: 'Achat de Planètes Mk2', cost: 44700, desc: 'Avancée majeure en Finance.', req: ['r_finance_11'] },
  'r_finance_13': { id: 'r_finance_13', name: 'Monopole de l'Univers Mk2', cost: 52200, desc: 'Avancée majeure en Finance.', req: ['r_finance_12'] },
  'r_finance_14': { id: 'r_finance_14', name: 'Hyper-inflation Maîtrisée Mk2', cost: 60300, desc: 'Avancée majeure en Finance.', req: ['r_finance_13'] },
  'r_finance_15': { id: 'r_finance_15', name: 'Monnaie Universelle Mk3', cost: 69000, desc: 'Avancée majeure en Finance.', req: ['r_finance_14'] },
  'r_finance_16': { id: 'r_finance_16', name: 'Capitalisme Absolu Mk3', cost: 78300, desc: 'Avancée majeure en Finance.', req: ['r_finance_15'] },
  'r_finance_17': { id: 'r_finance_17', name: 'Optimisation Quantique Mk3', cost: 88200, desc: 'Avancée majeure en Finance.', req: ['r_finance_16'] },
  'r_finance_18': { id: 'r_finance_18', name: 'Asservissement par la Dette Mk3', cost: 98700, desc: 'Avancée majeure en Finance.', req: ['r_finance_17'] },
  'r_finance_19': { id: 'r_finance_19', name: 'Achat de Planètes Mk3', cost: 109800, desc: 'Avancée majeure en Finance.', req: ['r_finance_18'] },
  'r_finance_20': { id: 'r_finance_20', name: 'Monopole de l'Univers Mk3', cost: 121500, desc: 'Avancée majeure en Finance.', req: ['r_finance_19'] },
  'r_finance_21': { id: 'r_finance_21', name: 'Hyper-inflation Maîtrisée Mk3', cost: 133800, desc: 'Avancée majeure en Finance.', req: ['r_finance_20'] },
  'r_finance_22': { id: 'r_finance_22', name: 'Monnaie Universelle Mk4', cost: 146700, desc: 'Avancée majeure en Finance.', req: ['r_finance_21'] },
  'r_finance_23': { id: 'r_finance_23', name: 'Capitalisme Absolu Mk4', cost: 160200, desc: 'Avancée majeure en Finance.', req: ['r_finance_22'] },
  'r_finance_24': { id: 'r_finance_24', name: 'Optimisation Quantique Mk4', cost: 174300, desc: 'Avancée majeure en Finance.', req: ['r_finance_23'] },
  'r_finance_25': { id: 'r_finance_25', name: 'Asservissement par la Dette Mk4', cost: 189000, desc: 'Avancée majeure en Finance.', req: ['r_finance_24'] },
  'r_finance_26': { id: 'r_finance_26', name: 'Achat de Planètes Mk4', cost: 204300, desc: 'Avancée majeure en Finance.', req: ['r_finance_25'] },
  'r_finance_27': { id: 'r_finance_27', name: 'Monopole de l'Univers Mk4', cost: 220200, desc: 'Avancée majeure en Finance.', req: ['r_finance_26'] },
  'r_finance_28': { id: 'r_finance_28', name: 'Hyper-inflation Maîtrisée Mk4', cost: 236700, desc: 'Avancée majeure en Finance.', req: ['r_finance_27'] },
  'r_finance_29': { id: 'r_finance_29', name: 'Monnaie Universelle Mk5', cost: 253800, desc: 'Avancée majeure en Finance.', req: ['r_finance_28'] },
  'r_finance_30': { id: 'r_finance_30', name: 'Capitalisme Absolu Mk5', cost: 271500, desc: 'Avancée majeure en Finance.', req: ['r_finance_29'] },
};
